### ISSUE TITLE
M1 Mac での yarn install エラーを解消

### ISSUE THREAD

**Issue by kennyttotheleft** [wagumi/wagumi#26]
下記の M1 Mac 環境だとプロジェクトルートからの yarn install が失敗してしまうため、回避策を追加するか相談させてください。

## 対象環境

MacBook Pro (13-inch, M1, 2020)

```shell
% sw_vers
ProductName:    macOS
ProductVersion: 11.6.1
BuildVersion:   20G224
```

## バージョン情報
node
* v14.17.6 (npm: v6.14.15)
* v14.18.1 (npm: v6.14.15)

## エラーメッセージ

```shell
wagumi% yarn install
yarn install v1.9.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[-------------------------------------------------------------------------------------------------------------------------------------------] 0/2047(node:3778) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
error An unexpected error occurred: "https://registry.yarnpkg.com/prettier/-/prettier-2.5.0.tgz: incorrect data check".
info If you think this is a bug, please open a bug report with the information provided in "/Users/kensuke/Documents/workspace/wagumi/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error https://registry.yarnpkg.com/@next/swc-darwin-arm64/-/swc-darwin-arm64-12.0.7.tgz: incorrect data check
error https://registry.yarnpkg.com/@next/swc-darwin-x64/-/swc-darwin-x64-12.0.7.tgz: incorrect data check
error https://registry.yarnpkg.com/@next/swc-linux-arm64-gnu/-/swc-linux-arm64-gnu-12.0.7.tgz: incorrect data check
error https://registry.yarnpkg.com/@next/swc-linux-arm-gnueabihf/-/swc-linux-arm-gnueabihf-12.0.7.tgz: incorrect data check
error https://registry.yarnpkg.com/@next/swc-android-arm64/-/swc-android-arm64-12.0.7.tgz: incorrect data check
error https://registry.yarnpkg.com/@next/swc-linux-x64-gnu/-/swc-linux-x64-gnu-12.0.7.tgz: incorrect data check
error https://registry.yarnpkg.com/@next/swc-linux-arm64-musl/-/swc-linux-arm64-musl-12.0.7.tgz: incorrect data check
error https://registry.yarnpkg.com/@next/swc-win32-arm64-msvc/-/swc-win32-arm64-msvc-12.0.7.tgz: incorrect data check
error https://registry.yarnpkg.com/@next/swc-linux-x64-musl/-/swc-linux-x64-musl-12.0.7.tgz: incorrect data check
error https://registry.yarnpkg.com/@next/swc-win32-ia32-msvc/-/swc-win32-ia32-msvc-12.0.7.tgz: incorrect data check
error https://registry.yarnpkg.com/@next/swc-win32-x64-msvc/-/swc-win32-x64-msvc-12.0.7.tgz: incorrect data check
wagumi% 
```

## 回避策（案）
- 開発用 Docker コンテナを追加

**Comment by shunkakinoki** [comment]
原因たぶん分かりました！今修正pushしますね。少々お待ちください…！

**Comment by shunkakinoki** [comment]
ただ確かに、こちらdockerに移るのもありです。🙆‍♂️

**Comment by shunkakinoki** [comment]
こちらでchecksum再生成させていただいたので、再度確認していただくことはできますでしょうか。🙌

https://github.com/wagumi/wagumi/pull/28

**Comment by kennyttotheleft** [comment]
checksum 再作成ありがとうございます 🙏 

再実行してみたところ、zlib.js 関連のエラーが出てしまうので
一旦、フィードバックさせていただきました。

M1 Mac 固有の挙動で、今の所、そこまで優先度は高くなさそうなトピックと思いますので
引き続き、回避策を調査してみようと思います 💨 

### yarn-error.log（抜粋）

Yarn version: 
  1.9.2

Node version: 
  14.18.1

Platform: 
  darwin x64

Trace: 
  Error: incorrect data check
      at Zlib.zlibOnError [as onerror] (zlib.js:187:17)

### yarn install 実行結果

```shell
wagumi% yarn install
yarn install v1.9.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 0/2020(node:13786) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
error An unexpected error occurred: "https://registry.yarnpkg.com/@typescript-eslint/eslint-plugin/-/eslint-plugin-5.6.0.tgz: incorrect data check".
info If you think this is a bug, please open a bug report with the information provided in "/Users/kensuke/Documents/workspace/kennyttotheleft/wagumi/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by sakanosita** [comment]
ぼくもM1 Macを使ってます。
違うエラーが出たみたいです。ぼくも自分なりに解決策を調べてみます。

```
sakanosita@chimney wagumi % sw_vers
ProductName:	macOS
ProductVersion:	11.5.2
BuildVersion:	20G95
sakanosita@chimney wagumi % node -v
v14.17.6
sakanosita@chimney wagumi % yarn -v
1.22.11
```

<details>

```
 % yarn install
yarn install v1.22.11
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
info @next/swc-linux-arm64-musl@12.0.7: The platform "darwin" is incompatible with this module.
info "@next/swc-linux-arm64-musl@12.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info @next/swc-win32-ia32-msvc@12.0.7: The platform "darwin" is incompatible with this module.
info "@next/swc-win32-ia32-msvc@12.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info @next/swc-win32-ia32-msvc@12.0.7: The CPU architecture "arm64" is incompatible with this module.
info @next/swc-win32-arm64-msvc@12.0.7: The platform "darwin" is incompatible with this module.
info "@next/swc-win32-arm64-msvc@12.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info @next/swc-linux-arm-gnueabihf@12.0.7: The platform "darwin" is incompatible with this module.
info "@next/swc-linux-arm-gnueabihf@12.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info @next/swc-linux-arm-gnueabihf@12.0.7: The CPU architecture "arm64" is incompatible with this module.
info @next/swc-darwin-x64@12.0.7: The CPU architecture "arm64" is incompatible with this module.
info "@next/swc-darwin-x64@12.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info @next/swc-linux-arm64-gnu@12.0.7: The platform "darwin" is incompatible with this module.
info "@next/swc-linux-arm64-gnu@12.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info @next/swc-linux-x64-gnu@12.0.7: The platform "darwin" is incompatible with this module.
info "@next/swc-linux-x64-gnu@12.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info @next/swc-linux-x64-gnu@12.0.7: The CPU architecture "arm64" is incompatible with this module.
info @next/swc-android-arm64@12.0.7: The platform "darwin" is incompatible with this module.
info "@next/swc-android-arm64@12.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info @next/swc-linux-x64-musl@12.0.7: The platform "darwin" is incompatible with this module.
info "@next/swc-linux-x64-musl@12.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info @next/swc-linux-x64-musl@12.0.7: The CPU architecture "arm64" is incompatible with this module.
info @next/swc-win32-x64-msvc@12.0.7: The platform "darwin" is incompatible with this module.
info "@next/swc-win32-x64-msvc@12.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info @next/swc-win32-x64-msvc@12.0.7: The CPU architecture "arm64" is incompatible with this module.
[3/4] 🔗  Linking dependencies...
warning " > eslint-config-next@12.0.7" has unmet peer dependency "next@>=10.2.0".
warning "eslint-plugin-tailwindcss > tailwindcss@2.2.19" has unmet peer dependency "autoprefixer@^10.0.2".
warning "workspace-aggregator-d89a2d95-10cd-44e9-8947-a27a1e0daffb > @wagumi/airdrop > autoprefixer@10.4.0" has unmet peer dependency "postcss@^8.1.0".
warning "workspace-aggregator-d89a2d95-10cd-44e9-8947-a27a1e0daffb > @wagumi/airdrop > tailwindcss@3.0.0" has unmet peer dependency "postcss@^8.0.9".
warning "workspace-aggregator-d89a2d95-10cd-44e9-8947-a27a1e0daffb > @wagumi/bot > ts-node@10.4.0" has unmet peer dependency "@types/node@*".
warning "workspace-aggregator-d89a2d95-10cd-44e9-8947-a27a1e0daffb > @wagumi/contracts > @typechain/ethers-v5@8.0.5" has unmet peer dependency "@ethersproject/bytes@^5.0.0".
warning "workspace-aggregator-d89a2d95-10cd-44e9-8947-a27a1e0daffb > @wagumi/contracts > @typechain/ethers-v5@8.0.5" has unmet peer dependency "@ethersproject/abi@^5.0.0".
warning "workspace-aggregator-d89a2d95-10cd-44e9-8947-a27a1e0daffb > @wagumi/contracts > @typechain/hardhat@3.0.0" has unmet peer dependency "lodash@^4.17.15".
warning "workspace-aggregator-d89a2d95-10cd-44e9-8947-a27a1e0daffb > @wagumi/contracts > hardhat-deploy@0.9.14" has unmet peer dependency "@ethersproject/hardware-wallets@^5.0.14".
warning "workspace-aggregator-d89a2d95-10cd-44e9-8947-a27a1e0daffb > @wagumi/airdrop > next > @next/react-dev-overlay@12.0.7" has incorrect peer dependency "react@^17.0.2".
warning "workspace-aggregator-d89a2d95-10cd-44e9-8947-a27a1e0daffb > @wagumi/airdrop > next > @next/react-dev-overlay@12.0.7" has incorrect peer dependency "react-dom@^17.0.2".
warning "workspace-aggregator-d89a2d95-10cd-44e9-8947-a27a1e0daffb > @wagumi/airdrop > next > use-subscription@1.5.1" has incorrect peer dependency "react@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-d89a2d95-10cd-44e9-8947-a27a1e0daffb > @wagumi/airdrop > next > styled-jsx > @babel/plugin-syntax-jsx@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning Workspaces can only be enabled in private projects.
[4/4] 🔨  Building fresh packages...
[6/17] ⠁ keccak
[2/17] ⠁ canvas
[12/17] ⠁ keccak
[8/17] ⠁ keccak
error /Users/sakanosita/ghq/github.com/wagumi/wagumi/node_modules/canvas: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: /Users/sakanosita/ghq/github.com/wagumi/wagumi/node_modules/canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.7
node-pre-gyp info using node@14.17.6 | darwin | arm64
node-pre-gyp info check checked for "/Users/sakanosita/ghq/github.com/wagumi/wagumi/node_modules/canvas/build/Release/canvas.node" (not found)
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-darwin-unknown-arm64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-darwin-unknown-arm64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@14.17.6 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-darwin-unknown-arm64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@14.17.6 | darwin | arm64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@14.17.6 | darwin | arm64
gyp info find Python using Python version 3.8.2 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/sakanosita/ghq/github.com/wagumi/wagumi/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/sakanosita/ghq/github.com/wagumi/wagumi/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/sakanosita/ghq/github.com/wagumi/wagumi/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/sakanosita/Library/Caches/node-gyp/14.17.6/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/sakanosita/Library/Caches/node-gyp/14.17.6',
gyp info spawn args   '-Dnode_gyp_dir=/Users/sakanosita/ghq/github.com/wagumi/wagumi/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/sakanosita/Library/Caches/node-gyp/14.17.6/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/sakanosita/ghq/github.com/wagumi/wagumi/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/sakanosita/ghq/github.com/wagumi/wagumi/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.6.0
gyp ERR! command "/Users/sakanosita/.anyenv/envs/nodenv/versions/14.17.6/bin/node" "/Users/sakanosita/ghq/github.com/wagumi/wagumi/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/sakanosita/ghq/github.com/wagumi/wagumi/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/sakanosita/ghq/github.com/wagumi/wagumi/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /Users/sakanosita/ghq/github.com/wagumi/wagumi/node_modules/canvas
gyp ERR! node -v v14.17.6
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/sakanosita/.anyenv/envs/nodenv/versions/14.17.6/bin/node /Users/sakanosita/ghq/github.com/wagumi/wagumi/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/sakanosita/ghq/github.com/wagumi/wagumi/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/sakanosita/ghq/github.com/wagumi/wagumi/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/sakanosita/ghq/github.com/wagumi/wagumi/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Darwin 20.6.0
node-pre-gyp ERR! command "/Users/sakanosita/.anyenv/envs/nodenv/versions/14.17.6/bin/node" "/Users/sakanosita/ghq/github.com/wagumi/wagumi/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/sakanosita/ghq/github.com/wagumi/wagumi/node_modules/canvas
node-pre-gyp ERR! node -v v14.17.6
node-pre-gyp ERR! node-pre-gyp -v v1.0.7
node-pre-gyp ERR! not ok
```

</details>

**Comment by shunkakinoki** [comment]
node v14.18.1
yarn v1.22.17
でした！（自分の環境は

**Comment by sakanosita** [comment]
以下のようにbrewで足りないパッケージを入れたら
ぼくのM1環境でもyarn install が通りました！
```
brew install pkg-config
brew install pixman
brew install cairo
brew install pango
yarn install
```

エラーメッセージでググって以下のサイトを参考にしてみました。
https://www.jianshu.com/p/86122ee6039c



## 試してもダメだった方法
yarn.lockを削除して、yarn installしてみたけど、同じエラーメッセージでした。

**Comment by kennyttotheleft** [comment]
上記でいただいた brew install を実行後に、node のバージョンを 
v16.13.0 に変更したところインストールが成功しました 🙏 🙏 🙏 

<details>
<summary>node v16.13.0 でのインストールログ（成功）</summary>
wagumi% yarn cache clean
yarn cache v1.22.17
success Cleared cache.
✨  Done in 1.89s.
wagumi% node -v
v16.13.0
wagumi% yarn install
yarn install v1.22.17
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > eslint-config-next@12.0.7" has unmet peer dependency "next@>=10.2.0".
warning "eslint-plugin-tailwindcss > tailwindcss@2.2.19" has unmet peer dependency "autoprefixer@^10.0.2".
warning "workspace-aggregator-374e8047-2406-4fdb-9b77-cb620f6b8e5d > @wagumi/airdrop > autoprefixer@10.4.0" has unmet peer dependency "postcss@^8.1.0".
warning "workspace-aggregator-374e8047-2406-4fdb-9b77-cb620f6b8e5d > @wagumi/airdrop > tailwindcss@3.0.0" has unmet peer dependency "postcss@^8.0.9".
warning "workspace-aggregator-374e8047-2406-4fdb-9b77-cb620f6b8e5d > @wagumi/bot > ts-node@10.4.0" has unmet peer dependency "@types/node@*".
warning "workspace-aggregator-374e8047-2406-4fdb-9b77-cb620f6b8e5d > @wagumi/contracts > @typechain/ethers-v5@8.0.5" has unmet peer dependency "@ethersproject/bytes@^5.0.0".
warning "workspace-aggregator-374e8047-2406-4fdb-9b77-cb620f6b8e5d > @wagumi/contracts > @typechain/ethers-v5@8.0.5" has unmet peer dependency "@ethersproject/abi@^5.0.0".
warning "workspace-aggregator-374e8047-2406-4fdb-9b77-cb620f6b8e5d > @wagumi/contracts > @typechain/hardhat@3.0.0" has unmet peer dependency "lodash@^4.17.15".
warning "workspace-aggregator-374e8047-2406-4fdb-9b77-cb620f6b8e5d > @wagumi/contracts > hardhat-deploy@0.9.14" has unmet peer dependency "@ethersproject/hardware-wallets@^5.0.14".
warning "workspace-aggregator-374e8047-2406-4fdb-9b77-cb620f6b8e5d > @wagumi/airdrop > next > @next/react-dev-overlay@12.0.7" has incorrect peer dependency "react@^17.0.2".
warning "workspace-aggregator-374e8047-2406-4fdb-9b77-cb620f6b8e5d > @wagumi/airdrop > next > @next/react-dev-overlay@12.0.7" has incorrect peer dependency "react-dom@^17.0.2".
warning "workspace-aggregator-374e8047-2406-4fdb-9b77-cb620f6b8e5d > @wagumi/airdrop > next > use-subscription@1.5.1" has incorrect peer dependency "react@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-374e8047-2406-4fdb-9b77-cb620f6b8e5d > @wagumi/airdrop > next > styled-jsx > @babel/plugin-syntax-jsx@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning Workspaces can only be enabled in private projects.
[4/4] 🔨  Building fresh packages...
$ patch-package
patch-package 6.4.7
Applying patches...
nft-art-generator@1.0.2 ✔
$ husky install
husky - Git hooks installed
✨  Done in 54.01s.
wagumi% 
</details>


僕の環境では以下の node バージョンでは
インストールに失敗してしまう状況でした。
- v14.17.6
- v14.18.1

<details>
<summary>node v14.18.1 のインストールログ</summary>
wagumi% node -v
v14.18.1
wagumi% yarn cache clean
yarn cache v1.22.17
success Cleared cache.
✨  Done in 0.07s.
wagumi% yarn install
yarn install v1.22.17
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
wagumi% 
</details>
<details>
<summary>node v14.17.6 のインストールログ</summary>
wagumi% yarn cache clean
yarn cache v1.22.17
success Cleared cache.
✨  Done in 0.07s.
wagumi% node -v
v14.17.6
wagumi% yarn install
yarn install v1.22.17
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/micromatch/-/micromatch-4.0.4.tgz: incorrect data check".
info If you think this is a bug, please open a bug report with the information provided in "/Users/kensuke/Documents/workspace/kennyttotheleft/wagumi/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
wagumi% 
</details>

**Comment by kennyttotheleft** [comment]
Mac M1 ユーザー環境で yarn install できることが確認できましたので、クローズさせていただきます 🙏 💨
